version: "3.4"

services:
  whisper-asr-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASR_MODEL=base
      - ASR_ENGINE=openai_whisper
      - ASR_DEVICE=cpu
    ports:
      - "11401:9000"

